spring:
  application:
    name: zuul-grey
server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    feign-client-grey: /api/hello/**

ribbon:
  ConnectTimeout: 1500
  ReadTimeout: 20000