spring:
  application:
    name: eureka
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # 在eureka server上注册自己以提供服务 作为server不需要
    fetchRegistry: false # 获取eureka server上的注册信息 作为server不需要
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
