server:
  port: 8080
spring:
  application:
    name: http-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 5000
USER-SERVER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

