server:
  port:
    8080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: hello_route
          uri: lb://hello-server
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
